import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/investor.dart';
import '../domain/investor_repository.dart';
import '../domain/investor_transaction.dart';
import '../domain/investor_transaction_type.dart';
import '../data/supabase_investor_repository.dart';

part 'investor_controller.g.dart';

@riverpod
class InvestorListController extends _$InvestorListController {
  @override
  FutureOr<List<Investor>> build() {
    return ref.watch(investorRepositoryProvider).getInvestors();
  }

  Future<void> refresh() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() => ref.read(investorRepositoryProvider).getInvestors());
  }

  Future<void> createInvestor(String fullName, String email, String? phone) async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() async {
      await ref.read(investorRepositoryProvider).createInvestor(fullName, email, phone);
      return ref.read(investorRepositoryProvider).getInvestors();
    });
  }
}

@riverpod
class InvestorDetailsController extends _$InvestorDetailsController {
  @override
  FutureOr<Investor?> build(String id) {
    return ref.watch(investorRepositoryProvider).getInvestorById(id);
  }

  Future<void> refresh() async {
    state = const AsyncLoading();
    state = await AsyncValue.guard(() => ref.read(investorRepositoryProvider).getInvestorById(id));
  }
}

@riverpod
class InvestorTransactionsController extends _$InvestorTransactionsController {
  @override
  FutureOr<List<InvestorTransaction>> build(String investorId) {
    return ref.watch(investorRepositoryProvider).getInvestorTransactions(investorId);
  }

  Future<bool> addTransaction({
    required String investorId,
    required double amount,
    required InvestorTransactionType type,
    String? description,
  }) async {
    final repository = ref.read(investorRepositoryProvider);
    
    // Business Rule Validation: Liquidity Guard for Withdrawals
    if (type == InvestorTransactionType.withdrawal) {
      final investor = await repository.getInvestorById(investorId);
      if (investor == null || investor.availableBalance < amount) {
        return false; // Insufficient funds
      }
    }

    state = const AsyncLoading();
    final result = await AsyncValue.guard(() async {
      await repository.addTransaction(InvestorTransaction(
        id: '', // Generated by DB
        investorId: investorId,
        amount: amount,
        type: type,
        createdAt: DateTime.now(),
        description: description,
      ));
      return repository.getInvestorTransactions(investorId);
    });

    state = result;
    return !result.hasError;
  }
}
