import 'package:riverpod_annotation/riverpod_annotation.dart';
import '../domain/investor.dart';
import '../domain/investor_repository.dart';
import '../domain/investor_transaction.dart';
import 'sources/investor_data_source.dart';
import 'sources/supabase_investor_data_source.dart';

part 'supabase_investor_repository.g.dart';

class SupabaseInvestorRepository implements InvestorRepository {
  final InvestorDataSource _dataSource;

  SupabaseInvestorRepository(this._dataSource);

  @override
  Future<List<Investor>> getInvestors() async {
    final data = await _dataSource.getInvestors();
    return data.map((json) => Investor.fromJson(json)).toList();
  }

  @override
  Future<Investor?> getInvestorById(String id) async {
    final data = await _dataSource.getInvestorById(id);
    if (data == null) return null;
    return Investor.fromJson(data);
  }

  @override
  Future<Investor> createInvestor(String fullName, String email, String? phone) async {
    final data = await _dataSource.createInvestor({
      'full_name': fullName,
      'email': email,
      'phone': phone,
    });
    return Investor.fromJson(data);
  }

  @override
  Future<List<InvestorTransaction>> getInvestorTransactions(String investorId) async {
    final data = await _dataSource.getInvestorTransactions(investorId);
    return data.map((json) => InvestorTransaction.fromJson(json)).toList();
  }

  @override
  Future<void> addTransaction(InvestorTransaction transaction) async {
    // Note: ID is generated by DB, createdAt is generated by DB.
    // We only send the necessary fields.
    await _dataSource.insertTransaction({
      'investor_id': transaction.investorId,
      'amount': transaction.amount,
      'type': transaction.type.name,
      'reference_id': transaction.referenceId,
      'description': transaction.description,
    });
  }

  @override
  Stream<Investor?> watchInvestor(String id) {
    return _dataSource.watchInvestor(id).map((data) {
      if (data == null) return null;
      return Investor.fromJson(data);
    });
  }
}

@Riverpod(keepAlive: true)
InvestorRepository investorRepository(InvestorRepositoryRef ref) {
  final dataSource = ref.watch(investorDataSourceProvider);
  return SupabaseInvestorRepository(dataSource);
}
